import sharp from "sharp";
import { test, expect, section, assertFits } from "./fixtures";

test("school identity, reports, grading and logo persist after reload", async ({ page, school }) => {
  await page.goto(`${school.baseURL}/settings`);
  await page.getByLabel("Official school name").fill("Verified School Identity");
  await section(page, "Reports and identity");
  await page.getByLabel("Report title").fill("Verified Term Report");
  const logo = await sharp({ create: { width: 32, height: 32, channels: 4, background: "#167349" } }).png().toBuffer();
  await page.getByLabel("Select logo").setInputFiles({ name: "test-school.png", mimeType: "image/png", buffer: logo });
  await expect(page.getByAltText("School logo preview")).toHaveAttribute("src", /^data:/);
  await section(page, "Grading scale");
  await page.getByLabel("Minimum", { exact: true }).fill("90");
  await page.getByLabel("Grade", { exact: true }).fill("A+");
  await page.getByLabel("Comment", { exact: true }).fill("Excellent");
  await page.getByRole("button", { name: "Add", exact: true }).click();
  await page.getByRole("button", { name: "Save settings", exact: true }).click();
  await expect(page.getByText("School settings saved.", { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByLabel("Official school name")).toHaveValue("Verified School Identity");
  await section(page, "Reports and identity");
  await expect(page.getByLabel("Report title")).toHaveValue("Verified Term Report");
  await expect(page.getByAltText("School logo preview")).toHaveAttribute("src", /^\/uploads\//);
  expect(await page.getByAltText("School logo preview").evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true);
  const snapshot = await (await page.request.get(`${school.baseURL}/api/app/snapshot`, { headers: school.headers })).json();
  expect(snapshot.schoolSettings.gradingScale).toContainEqual({ min: 90, grade: "A+", comment: "Excellent" });
  const branding = await (await page.request.get(`${school.baseURL}/api/public/schools/${school.slug}/branding`)).json();
  expect(branding.name).toBe("Verified School Identity");
  await assertFits(page);
});

test("multi-role account creation, role editing and first-login password change", async ({ page, browser, school }) => {
  await page.goto(`${school.baseURL}/settings`);
  await section(page, "Access control");
  const trigger = page.getByRole("button", { name: "Create account", exact: true });
  await trigger.click();
  let dialog = page.getByRole("dialog");
  await expect(dialog).toBeVisible();
  await dialog.getByRole("button", { name: "Close dialog" }).focus();
  await page.keyboard.press("Shift+Tab");
  await expect(dialog.getByRole("button", { name: "Create account", exact: true })).toBeFocused();
  await page.keyboard.press("Tab");
  await expect(dialog.getByRole("button", { name: "Close dialog" })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(trigger).toBeFocused();
  await trigger.click();
  await dialog.getByLabel("Full name", { exact: true }).pressSequentially("Smoke Test Account");
  await expect(dialog.getByLabel("Full name", { exact: true })).toHaveValue("Smoke Test Account");
  await dialog.getByLabel("Email address", { exact: true }).fill("smoke.account@example.test");
  await dialog.getByRole("checkbox", { name: "Accountant", exact: true }).check();
  await assertFits(page);
  await dialog.getByRole("button", { name: "Create account", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "Temporary password", exact: true })).toBeVisible();
  const temporaryPassword = await dialog.getByLabel("Temporary password", { exact: true }).inputValue();
  expect(temporaryPassword.length).toBe(20);
  await dialog.getByRole("button", { name: "Done", exact: true }).click();
  await page.reload();
  await section(page, "Access control");
  const account = page.getByRole("article").filter({ has: page.getByRole("heading", { name: "Smoke Test Account", exact: true }) });
  await expect(account.getByText("Teacher", { exact: true })).toBeVisible();
  await expect(account.getByText("Accountant", { exact: true })).toBeVisible();
  await account.getByRole("button", { name: "Edit account" }).click();
  await dialog.getByRole("checkbox", { name: "Teacher", exact: true }).uncheck();
  await dialog.getByRole("button", { name: "Save account", exact: true }).click();
  await expect(dialog).toBeHidden();
  const snapshot = await (await page.request.get(`${school.baseURL}/api/app/snapshot`, { headers: school.headers })).json();
  const user = snapshot.users.find((entry: { email: string }) => entry.email === "smoke.account@example.test");
  expect(user.roles).toEqual(["accountant"]);
  expect(user).not.toHaveProperty("temporaryPassword");
  const context = await browser.newContext({ viewport: page.viewportSize()! });
  try {
    const firstLogin = await context.newPage();
    await firstLogin.goto(`${school.baseURL}/login`);
    await firstLogin.getByLabel("Email address", { exact: true }).fill(user.email);
    await firstLogin.getByLabel("Password", { exact: true }).fill(temporaryPassword);
    await firstLogin.getByRole("button", { name: "Sign in", exact: true }).click();
    await expect(firstLogin.getByRole("heading", { name: "Create your private password" })).toBeVisible();
    await firstLogin.getByLabel("Temporary password", { exact: true }).fill(temporaryPassword);
    await firstLogin.getByLabel(/^New password/).fill(school.admin.password);
    await firstLogin.getByLabel("Confirm new password", { exact: true }).fill(school.admin.password);
    await firstLogin.getByRole("button", { name: "Change password", exact: true }).click();
    await expect(firstLogin.getByRole("heading", { name: "Create your private password" })).toBeHidden();
    await firstLogin.reload();
    await expect(firstLogin.getByRole("heading", { name: "Create your private password" })).toBeHidden();
    await assertFits(firstLogin);
    const session = await firstLogin.evaluate(() => localStorage.getItem("edu_postgres_access_token"));
    const fresh = await firstLogin.request.get(`${school.baseURL}/api/app/snapshot`, { headers: { ...school.headers, Authorization: `Bearer ${session}` } });
    expect(fresh.status()).toBe(200);
  } finally { await context.close(); }
});

test("subject persistence and canonical selectors across academic screens", async ({ page, school }) => {
  await page.goto(`${school.baseURL}/settings`);
  await section(page, "Subjects");
  await page.getByLabel("Subject name", { exact: true }).fill("Environmental Studies");
  await page.getByLabel("Code", { exact: true }).fill("ENV");
  await page.getByRole("button", { name: "Add subject", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Environmental Studies", exact: true })).toBeVisible();
  await page.reload();
  await section(page, "Subjects");
  await expect(page.getByRole("heading", { name: "Environmental Studies", exact: true })).toBeVisible();
  const subjects = await (await page.request.get(`${school.baseURL}/api/subjects`, { headers: school.headers })).json();
  expect(subjects.some((subject: { name: string; active: boolean }) => subject.name === "Environmental Studies" && subject.active)).toBe(true);
  await page.goto(`${school.baseURL}/grades`);
  const gradesSubject = page.locator("select").filter({ has: page.locator('option[value="Environmental Studies"]') });
  await gradesSubject.selectOption("Environmental Studies");
  await expect(gradesSubject).toHaveValue("Environmental Studies");
  await assertFits(page);
  await page.goto(`${school.baseURL}/timetable`);
  await page.getByRole("button", { name: "Add Entry", exact: true }).click();
  const timetableSubject = page.getByRole("dialog").locator("select").filter({ has: page.locator('option[value="Environmental Studies"]') });
  await timetableSubject.selectOption("Environmental Studies");
  await expect(timetableSubject).toHaveValue("Environmental Studies");
  await page.keyboard.press("Escape");
  await page.goto(`${school.baseURL}/academics`);
  await page.getByRole("button", { name: "Enter Marks", exact: true }).click();
  const academicSubject = page.getByRole("dialog").locator("select").filter({ has: page.locator('option[value="Environmental Studies"]') });
  await academicSubject.selectOption("Environmental Studies");
  await expect(academicSubject).toHaveValue("Environmental Studies");
  await assertFits(page);
  await page.keyboard.press("Escape");
});

test("fee configuration and collection persist with correct period balances", async ({ page, school }) => {
  await page.goto(`${school.baseURL}/fees`);
  await page.getByRole("tab", { name: "Fee configuration", exact: true }).click();
  await page.getByRole("button", { name: "Add fee structure", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("Class", { exact: true }).selectOption("P.1");
  await dialog.getByLabel("Term", { exact: true }).selectOption("Term 1");
  await dialog.getByLabel("Fee item 1 name", { exact: true }).fill("Tuition");
  await dialog.getByLabel("Fee item 1 amount", { exact: true }).fill("100000");
  await dialog.getByRole("button", { name: "Add item", exact: true }).click();
  await dialog.getByLabel("Fee item 2 name", { exact: true }).fill("Materials");
  await dialog.getByLabel("Fee item 2 amount", { exact: true }).fill("50000");
  await assertFits(page);
  await dialog.getByRole("button", { name: "Save structure", exact: true }).click();
  await expect(dialog).toBeHidden();
  await page.reload();
  const structures = await (await page.request.get(`${school.baseURL}/api/fee-structures`, { headers: school.headers })).json();
  expect(structures).toHaveLength(1);
  expect(structures[0].totalAmount).toBe(150000);
  await page.getByRole("button", { name: "Collect fees", exact: true }).click();
  await dialog.getByLabel("Student", { exact: true }).selectOption(school.students[0].id);
  await dialog.getByLabel("Amount (UGX)", { exact: true }).fill("175000");
  await dialog.getByLabel("Transaction date", { exact: true }).fill("2026-09-01");
  await dialog.getByRole("button", { name: "Record payment", exact: true }).click();
  await expect(dialog).toBeHidden();
  await page.reload();
  const result = await (await page.request.get(`${school.baseURL}/api/fees/balances`, { headers: school.headers })).json();
  const balance = result.balances.find((entry: { studentId: string }) => entry.studentId === school.students[0].id);
  expect(balance).toMatchObject({ standardFee: 150000, paidAmount: 175000, outstandingAmount: 0, creditAmount: 25000 });
  await page.getByPlaceholder("Search student or reference...").fill(school.students[0].reg);
  await expect(page.getByText(school.students[0].name, { exact: true }).filter({ visible: true })).toBeVisible();
  await assertFits(page);
});
